### ISSUE TITLE
Is it possible to disable the logging deriving from this command?

### ISSUE THREAD

**Issue by giandv** [evilwindowdog/itunesfs#2]
Is it possible log after launch "itinesfs command"? Or if this is not possible, can the itmsp file be generated without generating the output.xml?
![itmsp](https://user-images.githubusercontent.com/18395021/95913350-5eba5700-0da4-11eb-95e1-ca8d7f78f9d9.PNG)

**Comment by Petrakeas** [comment]
I haven't updated the script the last 6 years. I wasn't actually aware that it's still functional :) 

I think that it's easy to fork it and comment out the logging part.
